[package]
name = "kite-server"
version = "1.0.0"
authors = ["sunnysab <i@sunnysab.cn>"]
edition = "2021"
readme = "README.md"

# More details in https://doc.rust-lang.org/cargo/reference/profiles.html.
[profile.release]
opt-level = 3
lto = "thin"
overflow-checks = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html.
[dependencies]
# About web
poem = { version = "1.2" }
tokio = { version = "1.15" }
reqwest = { version = "0.11", features = ["rustls-tls", "gzip"] }

num-traits = "0.2"
num-derive = "0.3"
lazy_static = "1"
regex = "1"
chrono = { version = "0.4", features = ["serde"] }

fern = "0.6"
log = "0.4"

# Serialization and Deserialization.
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
serde_json = "1.0"

# Database
sqlx = { version = "0.5", default-features = false, features = ["runtime-tokio-rustls", "uuid", "chrono", "json", "postgres", "macros"] }

# Error handle
thiserror = "1"
anyhow = "1.0"
