[package]
name = "kite-server"
version = "0.9.0"
authors = ["sunnysab <sunnysab@yeah.net>"]
edition = "2018"
readme = "README.md"

# More details in https://doc.rust-lang.org/cargo/reference/profiles.html.
[profile.release]
opt-level = 3
lto = "thin"
overflow-checks = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html.
[dependencies]
# About actix.
actix-web = { version = "4.0.0-beta.8", default-features = false, features = ["rustls", "compress-brotli"] }
actix-service = "2"
actix-utils = "3"
actix-multipart = "0.4.0-beta.5"
awc = "3.0.0-beta.7"

# About common tools.
futures-util = "0.3"
tokio = { version = "1", features = ["full"] }
futures = "0.3"

rand = "0.7"
num-traits = "0.2"
num-derive = "0.3"

lazy_static = "1"
uuid = { version = "0.8", features = ["serde", "v4"] }
regex = "1"
sys-info = "0.9"

chrono = { version = "0.4", features = ["serde"] }

fern = "0.6"
log = "0.4"

# Serialization and Deserialization.
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
serde_json = "1.0"
bincode = "1.3"

# Web tools.
jsonwebtoken = "7"

# Database
sqlx = { version = "0.5", default-features = false, features = ["runtime-actix-rustls", "uuid", "chrono", "json", "postgres", "macros"] }

# Encryption and code
aes = "0.7"
base64 = "0.13"
block-modes = "0.8"
urlencoding = "1"

# Error handle
thiserror = "1"
anyhow = "1.0"
