# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "cache",
    "cache-macro",
    "kite",
    "loader",
    "service-v3",
]
