[package]
name = "kite-server"
version = "0.1.0"
authors = ["sunnysab <sunnysab@yeah.net>"]
edition = "2018"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# About actix.
actix-http = "1"
actix-web = { version = "2.0", features = ["rustls"] }
actix-rt = "1"
actix-service = "1.0.0"
actix-multipart = "0.2.0"
actix-files = "0.2"

# About common tools.
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"
num-traits = "0.2"
num-derive = "0.3"
chrono = { version = "0.4", features = ["serde"] }
failure = "0.1"
toml = "0.5"
lazy_static = "1"
uuid = { version = "0.8", features = ["serde", "v4"] }
fern = "0.6"
log = "0.4"
thiserror = "1"

# Serialization and Deserialization.
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Web tools.
sanitize-filename = "0.2"
jsonwebtoken = "7"
rustls = "0.16"

# Database, diesel orm.
sqlx = { version = "0.3", default-features = false, features = ["uuid", "chrono", "json", "postgres", "runtime-tokio", "macros"]}

