[package]
name = "kite-server"
version = "0.1.0"
authors = ["sunnysab <sunnysab@yeah.net>"]
edition = "2018"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-http = "1"
actix-web = { version = "2.0", features = ["rustls"] }
actix-rt = "1"
actix-service = "1.0.0"
actix-multipart = "0.2.0"
futures = "0.3"
num-traits = "0.2"
num-derive = "0.3"
chrono = { version = "0.4", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
failure = "0.1"
toml = "0.5"
jsonwebtoken = "7"
lazy_static = "1"
diesel = { version = "1.0.0", features = ["postgres", "r2d2", "serde_json", "chrono", "uuid"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
sanitize-filename = "0.2"
