[package]
name = "kite-server"
version = "1.0.0"
authors = ["sunnysab <i@sunnysab.cn>"]
edition = "2021"
readme = "README.md"

# More details in https://doc.rust-lang.org/cargo/reference/profiles.html.
[profile.release]
opt-level = 3
lto = "thin"
overflow-checks = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html.
[dependencies]
# About web
poem = { version = "1.2" }
tokio = { version = "1.15", features = ["parking_lot"] }
reqwest = { version = "0.11", features = ["rustls-tls", "gzip", "json"] }

# Html parser
scraper = "0.12"

uuid = { version = "0.8", features = ["serde", "v4"] }
num-traits = "0.2"
num-derive = "0.3"
once_cell = "1.9"
regex = "1"
chrono = { version = "0.4", features = ["serde"] }
validator = { version = "0.12", features = ["derive"] }
substring = "1.4"

fern = "0.6"
log = "0.4"

# Serialization, encoding and encryption.
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
serde_json = "1.0"

base64 = "0.13"
block-modes = "0.7"
aes = "0.6"
rsa = "0.5"
sha2 = "0.10"
rand = "0.8"
jsonwebtoken = "7.2"

# Database
sqlx = { version = "0.5", default-features = false, features = ["runtime-tokio-rustls", "uuid", "chrono", "json", "postgres", "macros"] }

# Error handle
thiserror = "1"
anyhow = "1.0"
