[package]
name = "kite-server"
version = "0.1.0"
authors = ["sunnysab <sunnysab@yeah.net>"]
edition = "2018"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# About actix.
actix-http = "1"
actix-web = { version = "2.0", features = ["rustls"] }
actix-rt = "1"
actix-service = "1.0.0"
actix-multipart = "0.2.0"
actix-web-httpauth = "0.4"

# About common tools.
futures = "0.3"
num-traits = "0.2"
num-derive = "0.3"
chrono = { version = "0.4", features = ["serde"] }
failure = "0.1"
toml = "0.5"
lazy_static = "1"

# Serialization and Deserialization.
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

# Web tools.
sanitize-filename = "0.2"
jsonwebtoken = "7"

# Database, diesel orm.
diesel = { version = "1.0.0", features = ["postgres", "r2d2", "serde_json", "chrono"] }
tokio-diesel = "0.3"

