[package]
name = "kite-server"
version = "0.1.0"
authors = ["sunnysab <sunnysab@yeah.net>"]
edition = "2018"
readme = "README.md"

# More details in https://doc.rust-lang.org/cargo/reference/profiles.html.
[profile.release]
opt-level = 3
lto = "thin"
overflow-checks = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html.
[dependencies]
# About network.
actix-http = "2.0"
actix-web = { version = "3.0", features = ["rustls"] }
actix-service = "1.0"
actix-multipart = "0.3.0"

# About common tools.

futures-util = "0.3"
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"

rand = "0.7"
num-traits = "0.2"
num-derive = "0.3"

lazy_static = "1"
uuid = { version = "0.8", features = ["serde", "v4"] }
regex = "1"
sys-info = "0.7"

chrono = { version = "0.4", features = ["serde"] }

fern = "0.6"
log = "0.4"

# Serialization and Deserialization.
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
serde_json = "1.0"
bincode = "1.3"

# Web tools.
sanitize-filename = "0.2"
jsonwebtoken = "7"

# Database
sqlx = { version = "0.4", default-features = false, features = ["runtime-tokio-rustls", "uuid", "chrono", "json", "postgres", "macros"]}

# Encryption and code
aes = "0.4"
base64 = "0.12"
block-modes = "0.5"
urlencoding = "1.0"

# Error handle
thiserror = "1"
anyhow = "1.0"