# Server config
[server]
# HTTP API service address.
# Unix socket is supported.
# bind = "/var/kite/api.socket"
bind = "0.0.0.0:80"
# Postgresql connection string.
# Unix socket is supported.
# db = "postgresql:///database?host=/var/run/postgresql&user=www"
db = "postgresql://user:password@address:port/database"
# Token secret for API.
secret = "secret"
# Directory path should be end with "\"
attachment = "D:\\tmp\\"

# Wechat platform config. Access https://mp.weixin.qq.com for details
[wechat]
# Miniprogram appid
appid = "111"
# Secret
secret = "111"

[host]
# Bind address, for accepting connections from agents
bind = "0.0.0.0:1040"
# Max agent connections
max = 32


