# HTTP API service address.
bind = "0.0.0.0:80"
# Postgresql connection string.
db = "postgresql://user:password@address:port/database"
# Token secret for API.
secret = "secret"
# Directory path should be end with "\"
attachment = "D:\\tmp\\"
# secret for weather APi
qweather_key = "secret"


# 静态 api 资源文件夹
static_api_dir = "/var/kite/web"