[package]
name = "service-v2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kite = { path = "../kite" }

async-trait = "0.1"
poem = "1.3"
poem-openapi = "*"