name: Rust

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test
      
    - name: Copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_SECRET }}
        source: target/release/kite-server
        target: ${{ secrets.DEPLOY_PATH }}/kite-server.tmp
        
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_SECRET }}
        script: |
          cp ${{ secrets.DEPLOY_PATH }}/kite-server-v2 ${{ secrets.DEPLOY_PATH }}/kite-server-v2.bak
          mv ${{ secrets.DEPLOY_PATH }}/kite-server.tmp/target/release/kite-server ${{ secrets.DEPLOY_PATH }}/kite-server-v2
          systemctl stop kite2.service
          systemctl start kite2.service