name: Rust check

on:
  push: { branches: [ master ] }
  pull_request: { branches: [ master ] }

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --force --recursive --remote

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: nightly
      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Restore cargo packages
        uses: actions/cache@v3
        env:
          cache-name: cache-cargo-registry
        with:
          path: "~/.cargo/"
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
